version: '3'
services:
    development:
        hostname: development
        tty: true
        build:
            context: .
        volumes:
            - ${CASUAL_REPO_ROOT}:/home/casual/git
            - /tmp/.X11-unix:/tmp/.X11-unix
            - casual:/opt/casual
        environment:
            - DISPLAY=${DISPLAY}

volumes:
    casual:
